env:
  global:
    #GH_TOKEN
    - secure: "BvAZHbm6mefR1WNwsyxnsQYRCSDkcb1FgE8h3iytz00kDjmSdW3rD6g1KanLDiC11YRKXrCHrNOSqXkySIWzZL6LcskOyl6IoWA21pFiCbjDSG+rX2Vs0RlNKYoZMhgVUu5mCwOaX6jxlPldT3F1YVU1RAF9+CmmsJ7f0L6u0AI="
    #AWS_S3_KEY
    - secure: "LZsAjEcOztXZOA4gPtMa+OcjoD8F3QZrNaXJ3cwxq36dgNZbKx5ftoDS5J19ddAuTckJmUOWGAXdzrWh/axETu2V/sJ6Km1aStdVz5v6i2wEn1TATz14kP8HG9v5iwhqPScd2tkh8WbhPGnr+2oYGUq7B5nZKheADKDsTcYApPw="
    #AWS_S3_SECRET
    - secure: "HP0yU/o2VM6jjiADJKU+e8KFza959cmmLPk76IIDgLq3z6LomtTXMNz82hV97UvwwlMVMmiKVOx5Nm05YPl5R3g7YkCZMyUglV2HpYflilOBWGJl1lO7oM4uHegCl9jbKgKZyEa1My9WeYTLDVKz2TZ6GfRfGy+Y4GYeFF+Ol9g="
    #PHONEGAP_TOKEN
    - secure: "Mliyv2Ih6Yh+XhMsqRaEiPjwBKC+4cgFHTkGzVCd76jE/+BhaY4S7QfJaMJM2z47nIquMoNALWmQVDQLjFHugp1YGsXf/AxXn85hJ5wmb+gGMiwRYvGJWu3hK9lPdHWWQ7s8ObttISlKJrLYZLMkRyzOVl0qBQNUlnNS3wR/CnU="
    - BUILD_ENV: ${TRAVIS_BRANCH}
install:
  - sudo apt-get install s3cmd

script: 
- ROOT_DIR=$(pwd)
- cd $ROOT_DIR/compile/
- ./close.sh

after_success: 
- cd $ROOT_DIR
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials

- source ./scripts/deploy/prepareDeploy.sh
- source ./scripts/deploy/s3/s3.sh
# - source ./scripts/deploy/phonegap/phoneGapDeploy.sh
# - ./scripts/deploy/gh-pages/gh-pagesDeploy.sh

#clean up
# - rm -rf ./tmp


